apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: taskflow
  labels:
    app: project-service
spec:
  type: ClusterIP
  selector:
    app: project-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
